#
#spring:
#  datasource:
#    name: youhuo
#    url: jdbc:mysql://localhost:3307/${spring.datasource.name}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT&nullCatalogMeansCurrent=true
##    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid: # Druid 【监控】相关的全局配置
#      web-stat-filter:
#        enabled: true #是否启用StatFilter默认值true
#        url-pattern: /*
#        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
#        session-stat-enable: true
#        session-stat-max-count: 10
#      stat-view-servlet:
#        # 是否启用statViewServlet配置
#        enabled: true
#        # 访问监控页面
#        url-pattern: "/druid/*"
#        # 禁止手动重置监控数据
#        reset-enable: false
#        # 设置监控页面的登陆名
#        login-username: admin
#        # 设置监控页面的登陆密码
#        login-password: admin
#      initial-size: 5 # 初始连接数
#      min-idle: 10 # 最小连接池数量
#      max-active: 20 # 最大连接池数量
#      max-wait: 600000 # 配置获取连接等待超时的时间，单位：毫秒
#      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒
#      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位：毫秒
#      max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位：毫秒
#      validation-query: SELECT 1 FROM DUAL # 配置检测连接是否有效
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false


--- #################### 数据库相关配置 ####################
#spring:
#  # 数据源配置项
#  autoconfigure:
#    exclude:
#      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 排除 Druid 的自动配置，使用 dynamic-datasource-spring-boot-starter 配置多数据源
#  datasource:
#    druid: # Druid 【监控】相关的全局配置
#      web-stat-filter:
#        enabled: true
#      stat-view-servlet:
#        enabled: true
#        allow: # 设置白名单，不填则允许所有访问
#        url-pattern: /druid/*
#        login-username: # 控制台管理用户名和密码
#        login-password:
#      filter:
#        stat:
#          enabled: true
#          log-slow-sql: true # 慢 SQL 记录
#          slow-sql-millis: 100
#          merge-sql: true
#        wall:
#          config:
#            multi-statement-allow: true
#    dynamic: # 多数据源配置
#      druid: # Druid 【连接池】相关的全局配置
#        initial-size: 5 # 初始连接数
#        min-idle: 10 # 最小连接池数量
#        max-active: 20 # 最大连接池数量
#        max-wait: 600000 # 配置获取连接等待超时的时间，单位：毫秒
#        time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒
#        min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位：毫秒
#        max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位：毫秒
#        validation-query: SELECT 1 FROM DUAL # 配置检测连接是否有效
#        test-while-idle: true
#        test-on-borrow: false
#        test-on-return: false
#      primary: master
#      datasource:
#        master:
#          name: youhuo
#          url: jdbc:mysql://400-infra.server.iocoder.cn:3306/${spring.datasource.dynamic.datasource.master.name}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT&nullCatalogMeansCurrent=true
#          driver-class-name: com.mysql.jdbc.Driver
#          username: root
#          password: root
#        slave: # 模拟从库，可根据自己需要修改 # 模拟从库，可根据自己需要修改
#
#          name: youhuo
#          url: jdbc:mysql://400-infra.server.iocoder.cn:3306/${spring.datasource.dynamic.datasource.slave.name}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT&nullCatalogMeansCurrent=true
#          driver-class-name: com.mysql.jdbc.Driver
#          username: root
#          password: root